### ISSUE TITLE
Not working in Blender 4.1 ALPHA

### ISSUE THREAD

**Issue by SakuraEntropia** [saturday06/VRM-Addon-for-Blender#408]
When I tried to import this extension in Blender 4.1 Alpha an error occured

`Traceback (most recent call last):
  File "D:\Blender\4.1\scripts\modules\addon_utils.py", line 402, in enable
    mod.register()
  File "C:\Users\David\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\VRM_Addon_for_Blender-release\__init__.py", line 51, in register
    from . import registration
  File "C:\Users\David\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\VRM_Addon_for_Blender-release\registration.py", line 29, in <module>
    from .common import preferences, shader
  File "C:\Users\David\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\VRM_Addon_for_Blender-release\common\shader.py", line 8, in <module>
    from bpy.types import (
ImportError: cannot import name 'ShaderNodeTexMusgrave' from 'bpy.types' (unknown location)

`

**Comment by saturday06** [comment]
Thanks for the report!

The error has been resolved with the newly released 2.20.28.

Please note that alpha versions may not work properly.
