### ISSUE TITLE
Version 2.20.1 is not working in Blender 4.0

### ISSUE THREAD

**Issue by 3dcinetv** [saturday06/VRM-Addon-for-Blender#304]
## Describe the bug
When I install the addon in Blender 4.0 alpha, the addon throws an error and doesn't install.

## To Reproduce

Traceback (most recent call last):
  File "E:\Program Files\blender-4\4.0\scripts\modules\addon_utils.py", line 400, in enable
    mod.register()
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\VRM_Addon_for_Blender-2_20_1\__init__.py", line 39, in register
    from . import registration
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\VRM_Addon_for_Blender-2_20_1\registration.py", line 13, in <module>
    from .common import preferences, shader
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\VRM_Addon_for_Blender-2_20_1\common\shader.py", line 257, in <module>
    from_socket: bpy.types.NodeSocketInterface, to_socket: bpy.types.NodeSocketInterface
AttributeError: 'module' object has no attribute 'NodeSocketInterface'

## Desktop (please complete the following information)

- Windows 10
- Blender 4.0 alpha
- Addon Version 2.20.1

The addon from January 20203, was working in Blender 4.0.

**Comment by saturday06** [comment]
Thank you for your report. I can't fix it right away, but will do so by the time Blender 4.0 is officially released.
